version: "3.8"

services:
  traefik:
    image: traefik:v2.10
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    networks:
      - app-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    configs:
      - source: traefik-config
        target: /etc/traefik/traefik.yml
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.traefik.rule=PathPrefix(`/`)"
        - "traefik.http.routers.traefik.service=api@internal"
        - "traefik.http.services.traefik.loadbalancer.server.port=8080"
        - "traefik.http.routers.catchall.rule=PathPrefix(`/`)"
        - "traefik.http.routers.catchall.entrypoints=web,websecure"
        - "traefik.http.routers.catchall.service=app"
        - "traefik.http.routers.catchall.middlewares=websocket"
        - "traefik.http.services.app.loadbalancer.sticky.cookie.name=traefik-sticky-cookie"
        - "traefik.http.services.app.loadbalancer.sticky.cookie.secure=true"
        - "traefik.http.middlewares.websocket.headers.customrequestheaders.Connection=Upgrade"
        - "traefik.http.middlewares.websocket.headers.customrequestheaders.Upgrade=websocket"
        - "traefik.http.middlewares.catchall-retry.retry.attempts=3"
        - "traefik.http.middlewares.catchall-retry.retry.initialinterval=500ms"

  app:
    image: ${DOCKER_IMAGE}
    networks:
      - app-network
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == worker
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.app.rule=PathPrefix(`/`)"
        - "traefik.http.services.app.loadbalancer.server.port=80"
        - "traefik.http.routers.app.entrypoints=web,websecure"
        - "traefik.http.services.app.loadbalancer.sticky.cookie.name=traefik-sticky-cookie"
        - "traefik.http.services.app.loadbalancer.sticky.cookie.secure=true"

networks:
  app-network:
    driver: overlay

configs:
  traefik-config:
    file: traefik.yml